class EverionKeys:
    all_vital = {'heart_rate', 'oxygen_saturation', 'perfusion_index', 'motion_activity', 'activity_classification',
                   'heart_rate_variability', 'respiration_rate', 'energy', 'core_temperature', 'temperature_local',
                   'barometer_pressure', 'gsr_electrode', 'health_score', 'relax_stress_intensity_score',
                   'sleep_quality_index_score', 'training_effect_score', 'activity_score', 'richness_score',
                   'blood_pulse_wave', 'number_of_steps', 'temperature_object', 'temperature_barometer'
                 }

    major_vital = {'heart_rate', 'oxygen_saturation', 'heart_rate_variability', 'respiration_rate',
                     'core_temperature'}

    short_names_vital = {
        "heart_rate": "HR",
        "oxygen_saturation": "SPO2",
        "perfusion_index": "PI",
        "motion_activity": "Motion",
        "activity_classification": "AC",
        "heart_rate_variability": "HRV",
        "respiration_rate": "RR",
        "energy": "E",
        "core_temperature": "Temp",
        "temperature_local": "TmpL",
        "barometer_pressure": "PB",
        "gsr_electrode": "GSR",
        "health_score": "Health",
        "relax_stress_intensity_score": "RStressI",
        "sleep_quality_index_score": "Sleep",
        "training_effect_score": "Training",
        "activity_score": "AS",
        "richness_score": "RS",
        "heart_rate_quality": "HRQ",
        "oxygen_saturation_quality": "SPO2Q",
        "blood_pulse_wave": "BPW",
        "number_of_steps": "Steps",
        "activity_classification_quality": "ACQ",
        "energy_quality": "EQ",
        "heart_rate_variability_quality": "HRVQ",
        "respiration_rate_quality": "RRQ",
        "core_temperature_quality": "CTempQ",
        "temperature_object": "TObj",
        "temperature_barometer": "TBaro"
    }

    tag_units_vital = {
        "6": "bpm",
        "7": "%",
        "8": "1",
        "9": "1",
        "11": "ms",
        "12": "bpm",
        "13": "cal/s",
        "15": "degC",
        "19": "degC",
        "20": "mbar",
        "21": "kOhm",
        "22": "%",
        "23": "%",
        "24": "%",
        "25": "%",
        "26": "%",
        "66": "%",
        "68": "%",
        "69": "%",
        "70": "1",
        "71": "1",
        "72": "%",
        "73": "%",
        "74": "%",
        "75": "%",
        "76": "%",
        "118": "degC",
        "119": "degC"
    }

    tag_names_vital = {
        "6": "heart_rate",
        "7": "oxygen_saturation",
        "8": "perfusion_index",
        "9": "motion_activity",
        "10": "activity_classification",
        "11": "heart_rate_variability",
        "12": "respiration_rate",
        "13": "energy",
        "15": "core_temperature",
        "19": "temperature_local",
        "20": "barometer_pressure",
        "21": "gsr_electrode",
        "22": "health_score",
        "23": "relax_stress_intensity_score",
        "24": "sleep_quality_index_score",
        "25": "training_effect_score",
        "26": "activity_score",
        "66": "richness_score",
        "68": "heart_rate_quality",
        "69": "oxygen_saturation_quality",
        "70": "blood_pulse_wave",
        "71": "number_of_steps",
        "72": "activity_classification_quality",
        "73": "energy_quality",
        "74": "heart_rate_variability_quality",
        "75": "respiration_rate_quality",
        "76": "core_temperature_quality",
        "118": "temperature_object",
        "119": "temperature_barometer"
    }

    tag_names_mixed_vital_raw = {'2.1': 'HR',
                                  '4.1': 'HRQ',
                                  '6.1': 'SPo2',
                                  '8.1': 'SPO2Q',
                                  '10.1': 'BloodPressure',
                                  '14.1': 'BloodPerfusion',
                                  '18.1': 'Activity',
                                  '20.1': 'Classification',
                                  '22.1': 'QualityClassification',
                                  '24.1': 'steps',
                                  '26.1': 'Energy',
                                 '28.1': 'RespRate',
                                 '29.1': 'HRV',
                                 '42.1': 'phase',
                                 '44.1': 'phase',
                                 '46.1': 'localtemp',
                                 '48.1': 'objtemp',
                                 '50.1': 'baromtemp',
                                 '52.1': 'pressure',
                                 }
    all_signals_mixed_vital_raw = {'HR', 'HRQ', 'SPo2', 'SPO2Q', 'BloodPressure',
                               'BloodPerfusion', 'Activity', 'Classification',
                               'QualityClassification', 'steps', 'Energy', 'RespRate',
                               'HRV', 'phase', 'phase', 'localtemp', 'objtemp', 'baromtemp', 'pressure'}

    medium_mixed_vital_raw = {'HR', 'HRV', 'SPo2', 'BloodPressure', 'Activity',
                               'Classification', 'steps', 'Energy', 'RespRate'}

    major_imove = {'HR', 'Activity', 'Classification', 'BloodPressure'}


    major_mixed_vital_raw = {'HR', 'HRV', 'SPo2', 'objtemp', 'RespRate'}

    short_names_mixed_vital_raw = {
        "HR": "HR",
        "SPo2": "SPO2",
        "BloodPerfusion": "BPerf",
        "Activity": "A",
        "Classification": "AC",
        "QualityClassification": "QAC",
        "HRV": "HRV",
        "RespRate": "RR",
        "Energy": "E",
        "localtemp": "TmpL",
        "HRQ": "HRQ",
        "SPO2Q": "SPO2Q",
        "BloodPressure": "BP",
        "steps": "Steps",
        "objtemp": "Temp",
        "baromtemp": "TBaro",
        "phase": "phase",
        "pressure": "pressure",
    }


    activity_class = {'0' : 'undefined',
                    '1' : 'resting',
                    '2' : 'walking_flat',
                    '3' : 'running_flat',
                    '4' : 'biking_flat',
                    '5' : 'walking_up',
                    '6' : 'running_up',
                    '7' : 'biking_up',
                    '8' : 'rowing',
                    '9' : 'other',
                    '10' : 'biking',
                    '11' : 'running',
                    '12' : 'walking',
                    '13' : 'walking_down',
                    '14' : 'running_down',
                    '15' : 'biking_down',
                    '16' : 'sitting',
                    '17' : 'standing',
                    '18' : 'driving_car',
                    '19' : 'driving_public',
                    '20' : 'sleeping',
                    '21' : 'awake',
                    '22' : 'ctrl_rest_med_ee',
                    '23' : 'relax_payin',
                    '24' : 'sleep_payin',
                    '25' : 'exercise_payin',
                    '26' : 'move_payin'
                    }
